image: cirrusci/flutter:stable

stages:
  - build
  
before_script:
  - flutter pub get
  - flutter clean

build:
  stage: build

  script:
    - flutter build apk --debug

  tags:
    - shared

  artifacts:
    paths:
      - build/app/outputs/flutter-apk/app-debug.apk

  only:
    - main
    - /^release.*$/