name: nc_passwords_app
description: A password manager app for Nextcloud passwords app.

publish_to: 'none'

version: 0.9.7+7

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^1.1.0
  crypto: ^2.1.5
  intl: ^0.16.1
  provider: ^4.3.2+2
  local_auth: ^0.6.3+1
  flutter_webview_plugin: ^0.3.11
  flutter_secure_storage: ^3.3.3
  http: ^0.12.2
  url_launcher: ^5.5.3
  favicon: ^1.0.13
  flutter_i18n: ^0.19.4
  autofill_service:
    path: ./plugins/autofill_service/

dev_dependencies:
  flutter_launcher_icons: "^0.8.1"

flutter:
  uses-material-design: true
  assets:
    - assets/i18n/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/launcher/icon.png"
