name: nc_passwords_app
description: A password manager app for Nextcloud's passwords app.

publish_to: 'none'

version: 20.12.0+13

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^1.1.0
  crypto: ^2.1.5
  intl: ^0.16.1
  provider: ^4.3.2+2
  local_auth: ^0.6.3+1
  flutter_webview_plugin: ^0.3.11
  flutter_secure_storage: ^3.3.3
  http: ^0.12.2
  url_launcher: ^5.5.3
  favicon: ^1.0.13
  flutter_i18n: ^0.20.0
  autofill_service:
    path: ./plugins/autofill_service/
  flutter_speed_dial: ^1.0.9
  cached_network_image: ^2.3.3
  flutter_cache_manager: ^2.0.0
  localstorage: ^3.0.0
  flutter_colorpicker: ^0.3.4

dev_dependencies:
  flutter_launcher_icons: "^0.8.1"

flutter:
  uses-material-design: true
  assets:
    - assets/i18n/
    - assets/launcher/

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/launcher/icon.png"
  adaptive_icon_background: "assets/launcher/icon_background.png"
  adaptive_icon_foreground: "assets/launcher/icon_foreground.png"
