name: nc_passwords_app
description: A password manager app for Nextcloud's passwords app.

publish_to: 'none'

version: 21.4.1+19

environment:
  sdk: '>=2.10.5-0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.1
  intl: ^0.17.0
  provider: ^5.0.0
  local_auth: ^1.1.1
  flutter_inappwebview: ^5.3.1
  flutter_secure_storage: ^4.1.0
  http: ^0.13.1
  url_launcher: ^6.0.3
  favicon: ^1.0.13
  flutter_i18n: ^0.22.3
  autofill_service:
    path: ./plugins/autofill_service/
  flutter_speed_dial: ^3.0.5
  cached_network_image: ^3.0.0
  flutter_cache_manager: ^3.0.1
  localstorage: ^4.0.0+1
  flutter_colorpicker: ^0.4.0
  flutter_sodium: ^0.2.0
  qrscan: ^0.3.1
  permission_handler: ^8.1.0
  device_apps: ^2.0.2
dev_dependencies:
  flutter_launcher_icons: ^0.9.0

flutter:
  uses-material-design: true
  assets:
    - assets/i18n/
    - assets/launcher/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Thin.ttf
          weight: 500
flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/launcher/icon.png"
  adaptive_icon_background: "assets/launcher/icon_background.png"
  adaptive_icon_foreground: "assets/launcher/icon_foreground.png"
